language: python
sudo: enabled
os: linux
python:
  - "3.6"
# command to install dependencies
install:
  - pip3 install retrying
  - pip3 install python-coveralls
# command to run tests
script:
  - coverage run test_rpn.py
  - coverage report

after_success:
  - coveralls
